---
title: "Road accidents"
author: "Selim Ach"
date: "10/15/2020"
output:
  pdf_document: default
  html_document: default
---

```{r, warning =FALSE, message=FALSE, echo = FALSE}

# loading library

library(readr)
library(OpenStreetMap)
library(tidyverse)
library(visdat)
library(ggthemes)

accidents <- read_csv("Data/accidents_Geneva.csv")

ggplot() +
  geom_point(
    data = accidents,
    mapping = aes(x = lon_wgs, y = lat_wgs),
    alpha = 0.05,
    color = "dodgerblue4"
  ) +
  theme_minimal() +
  labs(
    y = "Latitude",
    x = "Longitude",
    title = "Road accidents in Geneva",
    subtitle = "From 2010 to 2018",
    caption = "Source: SITG"
  )

```


```{r, warning =FALSE, message=FALSE, echo = FALSE}

map <- OpenStreetMap::openmap(
  upperLeft = c(46.183158, 6.107025),
  lowerRight = c(46.228066, 6.195431),
  type = "osm")

map_latlon <- openproj(map, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

autoplot.OpenStreetMap(map_latlon) +
  geom_point(
    data = accidents,
    mapping = aes(x = lon_wgs, y = lat_wgs),
    alpha = 0.05,
    color = "dodgerblue4"
  ) +
  labs(
    title = "Road accidents in Geneva",
    y = "Latitude",
    x = "Longitude",
    caption = "Source: SITG"
  ) +
  ylim(46.183158, 46.228066) +
  xlim(6.107025, 6.195431)+
  theme_void()+
    theme(plot.title = element_text(size = 14,hjust = 0.8, vjust = 1.5))
```
The map showing the location of all car accidents in Geneva. But are there more accidents during a rainy day ?

```{r, warning =FALSE, message=FALSE, echo = FALSE}

autoplot.OpenStreetMap(map_latlon) +
  geom_point(
    data = accidents,
    mapping = aes(x = lon_wgs, y = lat_wgs),
    alpha = 0.1,
    color = "dodgerblue4"
  ) +
  facet_wrap(vars(conditions_meteo))+
  labs(
    title = "Road accidents in Geneva",
    y = "Latitude",
    x = "Longitude",
    caption = "Source: SITG"
  ) +
  ylim(46.183158, 46.228066) +
  xlim(6.107025, 6.195431)+
  theme_void()+
    theme(plot.title = element_text(size = 14,hjust = 0.8, vjust = 1.5))
  

  

```


